export const roomType = ["Regular", "VIP", "ICU", "Deluxe", "Suite"];
export const roomStatus = ["available", "occupied", "maintenance"];
export const roomInfo = [
  {
    roomNumber: 1,
    roomType: "Regular",
    roomPrice: 10000,
    roomDescription: "Regular room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 2,
    roomType: "VIP",
    roomPrice: 20000,
    roomDescription: "VIP room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 3,
    roomType: "ICU",
    roomPrice: 30000,
    roomDescription: "ICU room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 4,
    roomType: "Deluxe",
    roomPrice: 40000,
    roomDescription: "Deluxe room",
    roomCapacity: 5,
    isFilled: false,
  },
  {
    roomNumber: 5,
    roomType: "Suite",
    roomPrice: 50000,
    roomDescription: "Suite room",
    roomCapacity: 4,
    isFilled: false,
  },
  {
    roomNumber: 6,
    roomType: "Regular",
    roomPrice: 10000,
    roomDescription: "Regular room",
    roomCapacity: 5,
    isFilled: false,
  },
  {
    roomNumber: 7,
    roomType: "VIP",
    roomPrice: 20000,
    roomDescription: "VIP room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 8,
    roomType: "ICU",
    roomPrice: 30000,
    roomDescription: "ICU room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 9,
    roomType: "Deluxe",
    roomPrice: 40000,
    roomDescription: "Deluxe room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 10,
    roomType: "Suite",
    roomPrice: 50000,
    roomDescription: "Suite room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 11,
    roomType: "Regular",
    roomPrice: 10000,
    roomDescription: "Regular room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 12,
    roomType: "VIP",
    roomPrice: 20000,
    roomDescription: "VIP room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 13,
    roomType: "ICU",
    roomPrice: 30000,
    roomDescription: "ICU room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 14,
    roomType: "Deluxe",
    roomPrice: 40000,
    roomDescription: "Deluxe room",
    roomCapacity: 2,
    isFilled: false,
  },
  {
    roomNumber: 15,
    roomType: "Suite",
    roomPrice: 50000,
    roomDescription: "Suite room",
    roomCapacity: 2,
    isFilled: false,
  },
];